### ISSUE TITLE
SV data

### ISSUE THREAD

**Issue by rmadupuri** [knowledgesystems/curation-scrum#1122]
1. 5 non-msk studies.
2. Game plan to convert to the format.

**Comment by sbabyanusha** [comment]
121 studies had Fusion files: https://docs.google.com/spreadsheets/d/1IjvJhEY6WANT4-D2NpMSlsv3oW2xDfDs1SwyewRKAko/edit#gid=0

1. 4 of them already have SV file.
2. we can curate SV files for 46 non-msk studies (data is available in supplementary files)
3. 42 msk studies

Further work:

1. 18 non-msk studies with fusion files needs to be investigated.
2. Curate SV files for the available msk studies.
