### ISSUE TITLE
Ryan new study

### ISSUE THREAD

**Issue by ritikakundra** [knowledgesystems/curation-scrum#1208]
https://www.cbioportal.org/study/summary?id=rcc_msk_2022  active with new samples
![image.png](https://images.zenhubusercontent.com/5c70616198f9e17a3d167f25/ed6cdd24-56f9-4a3c-97be-e6d08cdfda00)

**Comment by sbabyanusha** [comment]
https://triage.cbioportal.mskcc.org/study/summary?id=rcc_msk_2022
there is only one thyroid sample in the list.
