### ISSUE TITLE
Review 3 studies for upcoming public release

### ISSUE THREAD

**Issue by rmadupuri** [knowledgesystems/curation-scrum#1646]

**Comment by sbabyanusha** [comment]
- *Pancan_metaprism_2023* 
    - https://triage.cbioportal.mskcc.org/study/summary?id=pancan_metaprism_2023 - completed first round of review
- *mtnn_msk_2022*  (Took care of initial fixes)
    - missing gene panel thunderbolt49
    - Add one missing Thunderbolt profiled sample in the gene panel matrix file.
