### ISSUE TITLE
Cholangio Studies Curation

### ISSUE THREAD

**Issue by yichaoS** [knowledgesystems/curation-scrum#896]
Create study: Fujimoto study
- MAF
- Clinical
- meta data
- Import into Triage- http://triage.cbioportal.org/triage/study/summary?id=chol_riken_2015

Future:
- Add Fusion and release to public

**Comment by ritikakundra** [comment]
![Screen Shot 2021-04-29 at 2.56.57 PM (1).png](https://images.zenhubusercontent.com/5c70616198f9e17a3d167f25/422d2e0b-69d2-436d-9d82-7a10825f8b46)
